version: '3.3'
services:
  db:
    container_name: gloat-db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'gloat'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ~/gloat-task/mysql:/var/lib/mysql
volumes:
  mysql:
